project/admin/views.py
import os

from flask import Blueprint, render_template, request, flash, redirect, url_for, current_app
from flask_login import login_user, current_user, login_required, logout_user
from sqlalchemy.exc import IntegrityError

from project.models.models import User, Category, Product
from project.utils.decorator import admin_required
from project import db


admin_blueprint = Blueprint('admin', __name__, template_folder='templates')


@admin_blueprint.route('/admin/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        current_user = User.find_by_username(username)
        if not current_user:
            flash('ERROR! user not found.', 'error')
            return redirect(url_for('admin.dashboard'))

        if current_user.role != 'admin':
            flash('Permission denied. Admin only', 'error')
            return redirect(url_for('admin.dashboard'))

        if User.verify_hash(password, current_user.password):
            current_user.authenticated = True
            db.session.add(current_user)
            db.session.commit()
            login_user(current_user)

            return redirect(url_for('admin.dashboard'))
        else:
            db.session.rollback()
            flash('ERROR! Incorrect login credentials.', 'error')

    return render_template('login.html')


@admin_blueprint.route('/admin/logout')
@login_required
def logout():
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    return redirect(url_for('admin.login'))


@admin_blueprint.route('/admin/')
@login_required
def dashboard():
    user = current_user
    return render_template('dashboard.html', current_user=user)


# USERS ############################################
@admin_blueprint.route('/admin/users')
@login_required
def users():
    all_user = User.query.all()
    user = current_user
    return render_template('users.html', users=all_user, current_user=user)


@admin_blueprint.route('/admin/user_add', methods=['GET', 'POST'])
@login_required
def user_add():
    if request.method == 'POST':
        try:
            username = request.form.get('username')
            password = User.generate_hash(request.form.get('password'))
            is_admin = request.form.get('is-admin')
            if is_admin:
                new_user = User(username, password, role='admin')
            else:
                new_user = User(username, password)

            db.session.add(new_user)
            db.session.commit()
            return redirect(url_for('admin.users'))

        except IntegrityError:
            db.session.rollback()
            flash('ERROR! username ({}) already exists.'.format(username), 'error')

    return render_template('user_add.html')


@admin_blueprint.route('/admin/user_delete/<user_id>')
@login_required
def user_delete(user_id):
    user = User.find_by_id(user_id)
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('admin.users'))


@admin_blueprint.route('/admin/user_edit/<user_id>/', methods=['GET', 'POST'])
@login_required
def user_edit(user_id):
    user = User.find_by_id(user_id)
    if request.method == 'POST':
        try:
            is_admin = request.form.get('is-admin')
            password = request.form.get('password')

            user.username = request.form.get('username')
            # user.password = User.generate_hash(password)
            # if User.verify_hash(password, current_user.password):
            #     user.password = password

            user.address = request.form.get('address')
            if is_admin:
                user.role = 'admin'
            else:
                user.role = 'user'

            db.session.commit()
            return redirect(url_for('admin.users'))

        except IntegrityError:
            db.session.rollback()
            flash('ERROR! username ({}) already exists.'.format(user.username), 'error')

    return render_template('user_edit.html', user=user)


# Categories ############################################
@admin_blueprint.route('/admin/categories')
@login_required
def categories():
    all_category = Category.query.all()
    return render_template('categories.html', categories=all_category)

@admin_blueprint.route('/admin/category_add', methods=['GET', 'POST'])
@login_required
def category_add():
    if request.method == 'POST':
        try:
            category_name = request.form.get('category-name')
            new_category = Category(category_name)
            db.session.add(new_category)
            db.session.commit()
            return redirect(url_for('admin.categories'))

        except IntegrityError as e:
            db.session.rollback()
            flash('ERROR! ({}) '.format(e), 'error')

    return render_template('category_add.html')


@admin_blueprint.route('/admin/category_delete/<category_id>')
@login_required
def category_delete(category_id):
    category = Category.find_by_id(category_id)
    db.session.delete(category)
    db.session.commit()
    return redirect(url_for('admin.categories'))


@admin_blueprint.route('/admin/category_edit/<category_id>', methods=['GET', 'POST'])
@login_required
def category_edit(category_id):
    category = Category.find_by_id(category_id)
    if request.method == 'POST':
        try:
            category_name = request.form.get('category-name')
            category.name = category_name

            db.session.commit()
            return redirect(url_for('admin.categories'))

        except IntegrityError as e:
            db.session.rollback()
            flash('ERROR! ({}) '.format(e), 'error')

    return render_template('category_edit.html', category=category)

# Products ############################################
@admin_blueprint.route('/admin/products')
@login_required
def products():
    all_product = Product.query.all()
    return render_template('products.html', products=all_product, cat=Category)


@admin_blueprint.route('/admin/product_add', methods=['GET', 'POST'])
@login_required
def product_add():
    all_category = Category.query.all()
    if request.method == 'POST':
        try:
            product_name = request.form.get('product-name')
            product_price = request.form.get('product-price')
            product_description = request.form.get('product-description')
            product_image_file = request.files['product-image']
            if product_image_file:
                product_image = '{}-{}'.format(product_name, product_image_file.filename)
                basedir = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
                product_image_file.save(os.path.join(basedir, current_app.config['PRODUCT_IMAGE'], product_image))
            else:
                product_image = None

            product_stock = request.form.get('product-stock')
            product_category_id = request.form.get('product-category_id')
            is_top_product = request.form.get('is-top-product')
            new_product = Product(product_name, product_price, product_description, product_image, product_stock, product_category_id, is_top_product)
            db.session.add(new_product)
            db.session.commit()
            return redirect(url_for('admin.products'))

        except IntegrityError as e:
            db.session.rollback()
            flash('ERROR! ({}) '.format(e), 'error')

    return render_template('product_add.html', categories=all_category)


@admin_blueprint.route('/admin/product_delete/<product_id>')
@login_required
def product_delete(product_id):
    product = Product.find_by_id(product_id)
    db.session.delete(product)
    db.session.commit()
    return redirect(url_for('admin.products'))


@admin_blueprint.route('/admin/product_edit/<product_id>', methods=['GET', 'POST'])
@login_required
def product_edit(product_id):
    product = Product.find_by_id(product_id)
    all_category = Category.query.all()
    if request.method == 'POST':
        try:
            product_name = request.form.get('product-name')
            product_price = request.form.get('product-price')
            product_description = request.form.get('product-description')
            product_image_file = request.files['product-image']
            if product_image_file:
                product_image = '{}-{}'.format(product_name, product_image_file.filename)
                basedir = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
                product_image_file.save(os.path.join(basedir, current_app.config['PRODUCT_IMAGE'], product_image))
            else:
                product_image = None

            product_stock = request.form.get('product-stock')
            product_category_id = request.form.get('product-category_id')
            is_top_product = request.form.get('is-top-product')

            product.name = product_name
            product.price = product_price
            product.description = product_description
            if product_image_file:
                product.image = product_image
            product.stock = product_stock
            product.category = product_category_id
            product.is_top_product = False
            if is_top_product:
                product.is_top_product = True

            db.session.commit()
            return redirect(url_for('admin.products'))

        except IntegrityError as e:
            db.session.rollback()
            flash('ERROR! ({}) '.format(e), 'error')

    return render_template('product_edit.html', product=product, categories=all_category, cat=Category)

project/admin/templates/_form_macros.html
{% macro render_field(field) %}
  {{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
  </dd>
{% endmacro %}

project/admin/templates/categories.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
Categories
{% endblock %}

{% block body %}
{% include 'navbar.html' %}
{% include 'sidebar.html' %}
{% include 'allert_message.html' %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1 class="m-0 text-dark">Categories</h1>
              </div><!-- /.col -->
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item"><a href="#">Home</a></li>
                  <li class="breadcrumb-item active">Categories data</li>
                </ol>
              </div><!-- /.col -->
            </div><!-- /.row -->
          </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <section class="content">
          <div class="row">
            <div class="col-12">
              <div class="card">
                <div class="card-header">
                  <a href="{{ url_for('admin.category_add') }}" class="card-title">+ Add category</a>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for category in categories %}
                        <tr class="odd gradeX">
                            <td>{{ category.name }}</td>
                            <td>
                                <a href="{{ url_for('admin.category_delete', category_id=category.id) }}">Delete</a>
                                ||
                                <a href="{{ url_for('admin.category_edit', category_id=category.id) }}">Edit</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                </div>
                <!-- /.card-body -->
              </div>
              <!-- /.card -->
            </div>
            <!-- /.col -->
          </div>
          <!-- /.row -->
        </section>

    </div>
    {% include 'footer.html' %}
{% endblock %}

project/admin/templates/category_add.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
Categories
{% endblock %}

{% block body %}
{% include 'navbar.html' %}
{% include 'sidebar.html' %}
{% include 'allert_message.html' %}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Categories</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Categories data</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3>Add category</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <form role="form" action="{{ url_for('admin.category_add') }}" method="post">
                            <div class="card-body">
                                <div class="form-group">
                                    <label>Category name</label>
                                    <div class="nk-int-st">
                                        <input type="text" class="form-control input-sm" placeholder="category-name"
                                               name="category-name">
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>

                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

</div>

{% include 'footer.html' %}
{% endblock %}

project/admin/templates/footer.html
 <footer class="main-footer">
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.0.2-pre
    </div>
  </footer>

project/admin/templates/product_edit.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
Products
{% endblock %}

{% block body %}
{% include 'navbar.html' %}
{% include 'sidebar.html' %}
{% include 'allert_message.html' %}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Products</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Products data</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3>Edit product</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <form role="form" action="{{ url_for('admin.product_edit',  product_id=product.id) }}" method="post" enctype="multipart/form-data">
                            <div class="card-body">
                                <div class="form-group">
                                    <label>Product name</label>
                                    <div class="nk-int-st">
                                        <input type="text" class="form-control input-sm" placeholder="product name"
                                               name="product-name" value="{{product.name}}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Price</label>
                                    <div class="nk-int-st">
                                        <input type="text" class="form-control input-sm" placeholder="product price"
                                               name="product-price" value="{{product.price}}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Description</label>
                                    <textarea class="textarea" placeholder="Place some text here"
                                              style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"
                                              name="product-description">
                                    {{product.description}}
                                    </textarea>
                                </div>
                                <div class="form-group">
                                    <label>Image: {{product.image}}</label>
                                    <div class="nk-int-st">
                                        <input type="file" id="product-image" name="product-image">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Stock</label>
                                    <div class="nk-int-st">
                                        <input type="text" class="form-control input-sm" placeholder="stock total"
                                               name="product-stock" value="{{product.stock}}">
                                    </div>
                                </div>
                                 <div class="form-group">
                                    <label>Category</label>
                                     {% set Cat = cat.find_by_id(product.category) %}
                                    <select class="custom-select" name="product-category_id">
                                      <option value="{{product.category}}">{{Cat.name}}</option>
                                      {% for category in categories %}
                                      <option value="{{category.id}}">{{category.name}}</option>
                                      {% endfor %}
                                    </select>
                                 </div>
                                <div class="form-group">
                                    <label>Top Product ? (will show on slider)</label>
                                    <div class="nk-int-st">
                                        {% if product.is_top_product %}
                                            <input type="checkbox" name="is-top-product" checked/>
                                        {% else %}
                                        <input type="checkbox" name="is-top-product"/>
                                        {% endif %}
                                    </div>
                                 </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>

                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

</div>

{% include 'footer.html' %}
{% endblock %}

project/admin/templates/products.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
Products
{% endblock %}

{% block body %}
{% include 'navbar.html' %}
{% include 'sidebar.html' %}
{% include 'allert_message.html' %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1 class="m-0 text-dark">Products</h1>
              </div><!-- /.col -->
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item"><a href="#">Home</a></li>
                  <li class="breadcrumb-item active">Products data</li>
                </ol>
              </div><!-- /.col -->
            </div><!-- /.row -->
          </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <section class="content">
          <div class="row">
            <div class="col-12">
              <div class="card">
                <div class="card-header">
                  <a href="{{ url_for('admin.product_add') }}" class="card-title">+ Add product</a>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Price</th>
                            <th>Stock</th>
                            <th>Category</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for product in products %}
                        {% set Cat = cat.find_by_id(product.category) %}
                        <tr class="odd gradeX">
                            <td>{{ product.name }}</td>
                            <td>{{ product.price }}</td>
                            <td>{{ product.stock }}</td>
                            <td>{{ Cat.name }}</td>
                            <td>
                                <a href="{{ url_for('admin.product_delete', product_id=product.id) }}">Delete</a>
                                ||
                                <a href="{{ url_for('admin.product_edit', product_id=product.id) }}">Edit</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                </div>
                <!-- /.card-body -->
              </div>
              <!-- /.card -->
            </div>
            <!-- /.col -->
          </div>
          <!-- /.row -->
        </section>

    </div>
    {% include 'footer.html' %}
{% endblock %}

project/admin/templates/sidebar.html
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/" target="_blank" class="brand-link">
      <img src="{{ url_for('static', filename='admin/dist/img/AdminLTELogo.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">Flask Furniture</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{ url_for('static', filename='admin/dist/img/user2-160x160.jpg') }}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="" class="d-block">Hi {{ current_user.username }}, Welcome</a>
          <br>
          <a href="{{ url_for('admin.logout') }}">
            <button>
            logout
            </button>
          </a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
           <li class="nav-item">
            <a href="{{ url_for('admin.dashboard') }}" class="nav-link">
              <i class="nav-icon far fa-image"></i>
              <p>
                Dashboard
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ url_for('admin.users') }}" class="nav-link">
              <i class="nav-icon far fa-image"></i>
              <p>
                Users
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ url_for('admin.categories') }}" class="nav-link">
              <i class="nav-icon far fa-image"></i>
              <p>
                Categories
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ url_for('admin.products') }}" class="nav-link">
              <i class="nav-icon far fa-image"></i>
              <p>
                Products
              </p>
            </a>
          </li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-copy"></i>
              <p>
                Layout Options
                <i class="fas fa-angle-left right"></i>
                <span class="badge badge-info right">6</span>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="pages/layout/top-nav.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Top Navigation</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="pages/layout/boxed.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Boxed</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="pages/layout/fixed-sidebar.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Fixed Sidebar</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="pages/layout/fixed-topnav.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Fixed Navbar</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="pages/layout/fixed-footer.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Fixed Footer</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="pages/layout/collapsed-sidebar.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Collapsed Sidebar</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

project/admin/templates/users.html
{% extends "base.html" %}

{% block title %}
    Users
{% endblock %}


{% block body %}
     {% include 'navbar.html' %}

	{% include 'sidebar.html' %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1 class="m-0 text-dark">Users</h1>
              </div><!-- /.col -->
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item"><a href="#">Home</a></li>
                  <li class="breadcrumb-item active">Users data</li>
                </ol>
              </div><!-- /.col -->
            </div><!-- /.row -->
          </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <section class="content">
          <div class="row">
            <div class="col-12">
              <div class="card">
                <div class="card-header">
                  <h3 class="card-title">User data</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Username</th>
                            <th>Address</th>
                            <th>Register date</th>
                            <th>Account type</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in users %}
                        <tr class="odd gradeX">
                            <td>{{ user.username }}</td>
                            <td>{{ user.address }}</td>
                            <td>{{ user.register_on }}</td>
                            <td>{{ user.role }}</td>
                            <td>
                                <a href="{{ url_for('admin.user_delete', user_id=user.id) }}">Delete</a>
                                ||
                                <a href="{{ url_for('admin.user_edit', user_id=user.id) }}">Edit</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                </div>
                <!-- /.card-body -->
              </div>
              <!-- /.card -->
            </div>
            <!-- /.col -->
          </div>
          <!-- /.row -->
        </section>

    </div>
    {% include 'footer.html' %}
{% endblock %}